# Generated by Django 3.0.5 on 2020-04-22 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_type', models.CharField(choices=[('FOOD', 'Food'), ('TEGNOLOGY', 'Tegnology'), ('HOUSEHOLDS_ITEMS', 'Households_Items'), ('CLOTHING', 'Clothing'), ('HYGIENE', 'Hygiene'), ('GAMES', 'Games'), ('MATERNITY', 'Maternity'), ('MEDICINE', 'Medicine'), ('STATIONERY', 'Stationery')], default='', max_length=50)),
                ('state_type', models.CharField(choices=[('USED', 'Used'), ('NEW', 'New'), ('BROKEN', 'Broken')], default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
