# Generated by Django 3.0.5 on 2020-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category_image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='state_type',
            field=models.CharField(choices=[('USED', 'Used'), ('NEW', 'New'), ('BROKEN', 'Broken')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.ProductCategory'),
        ),
    ]
