# Generated by Django 3.0.5 on 2020-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200424_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_UNU_code',
            field=models.CharField(default='', max_length=50, verbose_name='UNU key'),
        ),
    ]
