# Generated by Django 3.0.5 on 2020-04-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200424_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_UNU_code',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
    ]
