# Generated by Django 3.0.5 on 2020-04-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200424_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_UNU_code',
        ),
    ]
