# Generated by Django 3.0.5 on 2020-05-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productcategory_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('slug', 'parent')},
        ),
    ]
