# Generated by Django 3.0.5 on 2020-05-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200508_2159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('parent',)},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
