# Generated by Django 3.0.5 on 2020-05-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200508_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('parent',)},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_type',
        ),
    ]
