# Generated by Django 3.0.5 on 2020-04-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200424_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_type',
            new_name='subcategory_type',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
