# Generated by Django 3.0.5 on 2020-05-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('parent',)},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
    ]
