# Generated by Django 3.0.5 on 2020-04-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200424_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='subcategory_type',
            new_name='category_type',
        ),
    ]
