# Generated by Django 3.0.5 on 2020-05-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200508_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'products categories'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_type',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
