# Generated by Django 3.0.5 on 2020-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200424_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(max_length=50),
        ),
    ]
