# Generated by Django 3.0.5 on 2020-04-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image',
        ),
    ]
