# Generated by Django 3.0.5 on 2020-04-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200424_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.ProductSubcategory'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='subcategory_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
