# Generated by Django 3.0.5 on 2020-05-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200512_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'productcategory', 'verbose_name_plural': 'productscategories'},
        ),
    ]
