# Generated by Django 3.0.5 on 2020-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200430_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='subcategory_type',
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='state_type',
            field=models.CharField(choices=[('USED', 'Used'), ('NEW', 'New'), ('BROKEN', 'Broken')], default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'parent')},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
