# Generated by Django 3.0.5 on 2020-05-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200513_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'productcategory', 'verbose_name_plural': 'productscategories'},
        ),
    ]
