# Generated by Django 3.0.5 on 2020-04-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20200430_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='ProductSubcategory',
        ),
    ]
