# Generated by Django 3.0.5 on 2020-05-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200517_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
