# Generated by Django 3.0.5 on 2020-05-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
