# Generated by Django 3.0.5 on 2020-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20200517_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
