# Generated by Django 3.0.5 on 2020-05-22 09:22

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_product_extra_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_image',
            field=models.ImageField(blank=True, upload_to=product.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=product.models.get_upload_path),
        ),
    ]
