# Generated by Django 3.0.5 on 2020-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_productinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinterest',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
