# Generated by Django 3.0.5 on 2020-08-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productinterest_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinterest',
            old_name='title',
            new_name='description',
        ),
    ]
