# Generated by Django 3.0.5 on 2020-08-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20200827_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinterest',
            name='slug',
        ),
    ]
