# Generated by Django 3.0.5 on 2020-08-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_remove_productinterest_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinterest',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
