# Generated by Django 3.0.5 on 2020-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_productinterest_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinterest',
            name='slug',
        ),
        migrations.AddField(
            model_name='productinterest',
            name='interested',
            field=models.BooleanField(default=False),
        ),
    ]
