# Generated by Django 3.0.5 on 2020-08-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wished_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
    ]
