# Generated by Django 3.0.5 on 2020-08-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20200831_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinterest',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
