# Generated by Django 3.0.5 on 2020-08-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_product_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered',
        ),
    ]
