# Generated by Django 3.0.5 on 2020-09-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_remove_product_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinterest',
            name='description',
        ),
    ]
