# Generated by Django 3.0.5 on 2020-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_remove_productinterest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Available', max_length=200),
        ),
    ]
