# Generated by Django 3.0.5 on 2020-09-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_product_received_from_my_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinterest',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='productinterest',
            name='status',
        ),
    ]
