# Generated by Django 3.0.5 on 2020-09-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodetails',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='ngodetails',
            name='website',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
