# Generated by Django 3.0.5 on 2020-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('NGO', 'N.G.O.')], default='CIVILIAN', max_length=50),
        ),
    ]
