# Generated by Django 3.0.5 on 2020-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('NGO', 'N.G.O.')], max_length=50),
        ),
    ]
