# Generated by Django 3.0.5 on 2020-04-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofiles', '0011_auto_20200429_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('NGO', 'N.G.O.')], default=None, max_length=50),
        ),
    ]
